//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AriasRomanJonathan_Proyecto1
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrestamosHerramientas
    {
        public int IDPrestamo { get; set; }
        public string CedulaIdentidad { get; set; }
        public string CodigoHerramienta { get; set; }
        public Nullable<System.DateTime> FechaPrestamo { get; set; }
        public Nullable<System.DateTime> FechaCompromisoDevolucion { get; set; }
        public Nullable<System.DateTime> FechaRealDevolucion { get; set; }
    
        public virtual Colaboradores Colaboradores { get; set; }
        public virtual Herramientas Herramientas { get; set; }
    }
}
